service: devnotnull-ui

frameworkVersion: ">=2.0.0"
variablesResolutionMode: 20210326
plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-prune-plugin

custom:
  ##
  serverless-offline:
    port: 3000 

  ##
  localDevStaticFolder: build

  ##
  siteName: devnotnull.com

  ## Retention
  prune:
    automatic: true
    includeLayers: true
    number: 10

  ## 
  deploymentBucket:
    versioning: true
    accelerate: true

  ##
  environment: ${opt:stage, 'development'}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10 
  region: ${opt:region, 'eu-west-2'}
  stackName: ${self:service}-${self:custom.environment}
  environment:
    NODE_RUNTIME_ENV: ${self:custom.environment}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: devnotnull-ui-${self:custom.environment}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - POST
              MaxAge: 3000
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref AssetsBucket
                  - /*
        Bucket: !Ref AssetsBucket

functions:
  server:
    handler: build/serverless.handler
    environment:
      NODE_RUNTIME_ENV: ${self:custom.environment}
    events:
      - http:
          path: / # this matches any path, the token 'any' doesn't mean anything special
          method: GET
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: GET