name: On merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: bump-tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        INITIAL_VERSION: 1.0.0
      
    - name: Branch name
      run: echo running on branch ${{ github.ref_name }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build:prod
