name: Feature branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-api:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBECONFIG_FILE: '${{ secrets.PROD_KUBECONFIG }}'

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        role-duration-seconds: 1200
        role-session-name: MySessionName

    - name: Branch name
      run: echo running on branch ${{ github.ref_name }}

    - run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
        
    - run: 'echo "$VPN_CONFIG" > config.ovpn'
      env:
        VPN_CONFIG: ${{secrets.VPN_CONFIG}}

    - run: 'mkdir ~/.kube && echo "$PROD_KUBECONFIG" > ~/.kube/config'
      env:
        PROD_KUBECONFIG: ${{secrets.PROD_KUBECONFIG}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved

    - name: Connect to VPN
      uses: kota65535/github-openvpn-connect-action@v1.0.2
      with:
        config_file: ./config.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build:prod:pure

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: alexbrown201/devnotnull-ui:${{ github.ref_name }} 
  
    - run: helm repo add devnotnull https://devnotnull-helm.s3.eu-west-2.amazonaws.com
    
    - run: helm repo update

    - name: Create S3 bucket
      run: aws s3api create-bucket --bucket devnotnull-ui-${{ github.ref_name }} --region us-east-1 || true

    - name: Copy S3 bucket assets
      run: aws s3 cp ./build s3://devnotnull-ui-${{ github.ref_name }} --recursive
      
    - run: |
        aws s3api put-bucket-cors --bucket devnotnull-ui-${{ github.ref_name }} --cors-configuration '{"CORSRules" : [{"AllowedHeaders":["*"],"AllowedMethods":["GET","HEAD", "POST"],"AllowedOrigins":["*"],"ExposeHeaders":[]}]}'
     
    - run: |
        aws s3api put-bucket-policy --bucket devnotnull-ui-${{ github.ref_name }} --policy '{"Version": "2008-10-17", "Statement": [{ "Sid": "AllowPublicRead", "Effect": "Allow", "Principal": { "AWS": "*" }, "Action": ["s3:GetObject"], "Resource": ["arn:aws:s3:::devnotnull-ui-${{ github.ref_name }}/*" ] }] }'

    - run: |
       helm upgrade --install devnotnull-ui-${{ github.ref_name }} devnotnull/nodejs \
        --version 2 \
        --set env.NODE_RUNTIME_ENV=development \
        --set env.CDN_BUCKET=${{ github.ref_name }} \
        --set image.repository=alexbrown201/devnotnull-ui:${{ github.ref_name }} \
        --set port=3000 \
        --set service.type=LoadBalancer \
        --set image.pullPolicy=Always \
        --set replicaCount=1
