name: Feature branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-app:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Branch name
      run: echo running on branch ${{ github.ref_name }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build:prod

    - name: Create S3 bucket
      run: aws s3api create-bucket --bucket devnotnull-sls-template-${{ github.ref_name }} --region us-east-1 || true

    - name: Copy S3 bucket assets
      run: aws s3 cp ./build s3://devnotnull-sls-template-${{ github.ref_name }} --recursive
      
    - run: |
        aws s3api put-bucket-cors --bucket devnotnull-sls-template-${{ github.ref_name }} --cors-configuration '{"CORSRules" : [{"AllowedHeaders":["*"],"AllowedMethods":["GET","HEAD", "POST"],"AllowedOrigins":["*"],"ExposeHeaders":[]}]}'
     
    - run: |
        aws s3api put-bucket-policy --bucket devnotnull-sls-template-${{ github.ref_name }} --policy '{"Version": "2008-10-17", "Statement": [{ "Sid": "AllowPublicRead", "Effect": "Allow", "Principal": { "AWS": "*" }, "Action": ["s3:GetObject"], "Resource": ["arn:aws:s3:::devnotnull-ui-${{ github.ref_name }}/*" ] }] }'
