name: Feature branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-app:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Branch name
      run: echo running on branch ${{ github.ref_name }}

    - run: npm install -g yarn

    - run: yarn install 

    - run: yarn build:prod
